In [17]:
import import_model as im
import re
import numpy as np

In [18]:
Al = im.import_model("cosmology_Aletheia.dat")

In [19]:
Al.loc[0]["z(4)"]

2.0

In [21]:
redshift_column = re.compile("z.+")
np.where(redshift_column.match(Al.columns))

TypeError: expected string or bytes-like object

In [22]:
for column in Al.columns:
    print(redshift_column.match(column))

None
None
None
None
None
None
None
None
None
None
None
None
None
None
<re.Match object; span=(0, 4), match='z(4)'>
<re.Match object; span=(0, 4), match='z(3)'>
<re.Match object; span=(0, 4), match='z(2)'>
<re.Match object; span=(0, 4), match='z(1)'>
<re.Match object; span=(0, 4), match='z(0)'>
None
None

In [23]:
Al

,Name,ombh2,omch2,n_s,A_s,OmB,OmC,OmM,OmK,OmL,...,w0,wa,EOmDE,z(4),z(3),z(2),z(1),z(0),Lbox,sigma8
0,Columbus_0,0.022445,0.120567,0.96,2.127238e-09,0.050000,0.268584,0.318584,0.00,0.681416,...,-1.00,0.00,-,2.000000,1.000000,0.570000,0.300000,0.0,1000.00000,0.82755
1,Columbus_1,0.022445,0.120567,0.96,1.785684e-09,0.074198,0.398570,0.472768,0.00,0.527232,...,-1.00,0.00,-,1.760980,0.859383,0.480044,0.247707,0.0,820.89552,0.71934
2,Columbus_2,0.022445,0.120567,0.96,2.484859e-09,0.035964,0.193186,0.229150,0.00,0.770850,...,-1.00,0.00,-,2.231260,1.137080,0.658633,0.352053,0.0,1179.10448,0.92490
3,Columbus_3,0.022445,0.120567,0.96,2.320710e-09,0.050000,0.268584,0.318584,0.00,0.681416,...,-0.85,0.00,-,2.100420,1.043750,0.589912,0.307371,0.0,1000.00000,0.82755
4,Columbus_4,0.022445,0.120567,0.96,1.995537e-09,0.050000,0.268584,0.318584,0.00,0.681416,...,-1.15,0.00,-,1.922590,0.964144,0.552929,0.293369,0.0,1000.00000,0.82755
5,Columbus_5,0.022445,0.120567,0.96,2.070770e-09,0.050000,0.268584,0.318584,0.00,0.681416,...,-1.00,-0.20,-,1.972600,0.990094,0.566389,0.298893,0.0,1000.00000,0.82755
6,Columbus_6,0.022445,0.120567,0.96,2.201964e-09,0.050000,0.268584,0.318584,0.00,0.681416,...,-1.00,0.20,-,2.031470,1.010790,0.573828,0.301056,0.0,1000.00000,0.82755
7,Columbus_7,0.022445,0.120567,0.96,1.929616e-09,0.050000,0.268584,0.318584,-0.05,0.731416,...,-1.00,0.00,-,1.938160,0.977826,0.560990,0.296787,0.0,1000.00000,0.82755
8,Columbus_8,0.022445,0.120567,0.96,2.292917e-09,0.050000,0.268584,0.318584,0.00,0.681416,...,-1.15,-,2e-5,2.019714,0.997056,0.564711,0.296864,0.0,1000.00000,0.82755

In [27]:
Al.loc[0]["w0"]

-1.0